# -*- coding: utf-8 -*-
"""chembl_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TNkeX4W549VwqbkmT2HvQkOg_e6nDKp
"""

import pandas as pd
import numpy as np
from chembl_webresource_client.new_client import new_client

def fetch_chembl_data(target_chembl_id, output_csv):
    activity = new_client.activity
    print(f"Fetching IC50 data for target: {target_chembl_id}")

    results = activity.filter(
        target_chembl_id=target_chembl_id,
        standard_type="IC50"
    )
    results = list(results)[:500]

    data = []
    for r in results:
        smiles = r.get("canonical_smiles")
        ic50 = r.get("standard_value")
        if smiles and ic50:
            data.append([smiles, ic50])

    df = pd.DataFrame(data, columns=["smiles", "IC50_nM"])
    df["IC50_nM"] = pd.to_numeric(df["IC50_nM"], errors="coerce")
    df = df[df["IC50_nM"] > 0]
    df["pIC50"] = 9 - np.log10(df["IC50_nM"])

    df.to_csv(output_csv, index=False)
    print(f"Saved dataset: {output_csv}")
    print(f"Rows collected: {len(df)}")

    return df